name: Label Pull Requests

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  label-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/label.yml
