name: lint-and-test

on:
  push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout action from GitHub'
        uses: actions/checkout@v2

      - name: 'Checkout node from GitHub'
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.*'

      - name: 'Get yarn cache directory path'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 'Get actions cache'
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Install yarn'
        run: yarn install --frozen-lockfile

      - name: 'Run lint'
        run: yarn lint

      # TODO: maybe use pa11y-ci ?
      - name: 'Run tests'
        run: yarn test && yarn test:axe
