name: lint-and-test

on:
  push:
    branches:
      - gh-actions
    branches-ignore:
      - master

# TODO: finish off action with names

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out from GitHub'
        uses: actions/checkout@v2

      - name: 'Checking out from GitHub'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn test:axe