name: Upload to S3

on:
  push:
    branches:
      - master
      - s3-auth-fix

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout action from GitHub'
        uses: actions/checkout@v2

      - name: 'Checkout node from GitHub'
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.*'

      - name: 'Get yarn cache directory path'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 'Get actions cache'
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Install yarn'
        run: yarn install --frozen-lockfile

      - name: 'Run gatsby build'
        run: yarn build

      - name: 'Run s3 gatsby plugin to deploy site'
        run: yarn deploy && aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
